/**
 * TypeScript Types for FilmForge
 *
 * Auto-generated by Claudery Blueprint Generator
 */

// ============================================
// USER & AUTH
// ============================================

export interface User {
  id: string;
  email: string;
  username?: string;
  displayName?: string;
  avatarUrl?: string;
  role: "user" | "admin";
  createdAt: Date;
  updatedAt: Date;
}

export interface Profile {
  id: string;
  username?: string;
  displayName?: string;
  avatarUrl?: string;
  bio?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Session {
  user: User;
  accessToken: string;
  expiresAt: Date;
}

// ============================================
// ENTITIES
// ============================================

export interface Server {
  id: string;
  userId: string;
  id: string;
  created_at: Date;
  updated_at: Date;
  user_id: string;
  name: string;
  description?: string;
  createdAt: Date;
  updatedAt: Date;
}

export type ServerCreateInput = Omit<Server, "id" | "userId" | "createdAt" | "updatedAt">;
export type ServerUpdateInput = Partial<ServerCreateInput>;

export interface Channel {
  id: string;
  userId: string;
  id: string;
  created_at: Date;
  updated_at: Date;
  user_id: string;
  name: string;
  description?: string;
  createdAt: Date;
  updatedAt: Date;
}

export type ChannelCreateInput = Omit<Channel, "id" | "userId" | "createdAt" | "updatedAt">;
export type ChannelUpdateInput = Partial<ChannelCreateInput>;

export interface Message {
  id: string;
  userId: string;
  id: string;
  created_at: Date;
  updated_at: Date;
  user_id: string;
  content: string;
  createdAt: Date;
  updatedAt: Date;
}

export type MessageCreateInput = Omit<Message, "id" | "userId" | "createdAt" | "updatedAt">;
export type MessageUpdateInput = Partial<MessageCreateInput>;

export interface User {
  id: string;
  userId: string;
  id: string;
  created_at: Date;
  updated_at: Date;
  user_id: string;
  username: string;
  email: string;
  createdAt: Date;
  updatedAt: Date;
}

export type UserCreateInput = Omit<User, "id" | "userId" | "createdAt" | "updatedAt">;
export type UserUpdateInput = Partial<UserCreateInput>;

// ============================================
// API RESPONSES
// ============================================

export interface ApiResponse<T> {
  data?: T;
  error?: {
    code: string;
    message: string;
    details?: unknown;
  };
}

export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    total: number;
    limit: number;
    offset: number;
    hasMore: boolean;
  };
}

// ============================================
// COMMON TYPES
// ============================================

export type SortOrder = "asc" | "desc";

export interface SortOptions {
  field: string;
  order: SortOrder;
}

export interface FilterOptions {
  search?: string;
  status?: string;
  dateFrom?: Date;
  dateTo?: Date;
}

export interface QueryOptions {
  limit?: number;
  offset?: number;
  sort?: SortOptions;
  filters?: FilterOptions;
}

// ============================================
// FORM TYPES
// ============================================

export interface FormState<T> {
  values: T;
  errors: Partial<Record<keyof T, string>>;
  touched: Partial<Record<keyof T, boolean>>;
  isSubmitting: boolean;
  isValid: boolean;
}

// ============================================
// UTILITY TYPES
// ============================================

export type WithId<T> = T & { id: string };
export type WithTimestamps<T> = T & { createdAt: Date; updatedAt: Date };
export type Nullable<T> = T | null;
export type Optional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;
